/**
 * Labels for concept `requirements` keys (camelCase in content/) in French and Arabic.
 * English labels are derived from the key itself with `formatKey`.
 */
import { formatKey } from '#lib/content.ts';
import type { Lang } from '#lib/i18n/index.svelte.ts';

const fr: Record<string, string> = {
	umbrellaField: 'Domaine englobant',
	subsumesMLandDL: 'Englobe le ML et le DL',
	includesRuleBasedSystems: 'Inclut les systèmes à base de règles',
	requiresDataOrHeuristics: 'Nécessite des données ou des heuristiques',
	requiresQualityData: 'Nécessite des données de qualité',
	probabilisticOutput: 'Sortie probabiliste',
	generalizationGoal: 'Objectif de généralisation',
	avoidsHardcodedRules: 'Évite les règles codées en dur',
	dataInfrastructure: 'Infrastructure de données',
	pipelineOrchestration: 'Orchestration de pipelines',
	dataQualityEnforcement: 'Contrôle de la qualité des données',
	schemaGovernance: 'Gouvernance des schémas',
	unlabeledDataOnly: 'Données non étiquetées uniquement',
	requiresDistanceMetric: 'Nécessite une mesure de distance',
	featureScalingCritical: 'Mise à l’échelle des variables cruciale',
	noGroundTruthLabels: 'Pas d’étiquettes de référence',
	labeledTrainingData: 'Données d’entraînement étiquetées',
	discreteTargetClasses: 'Classes cibles discrètes',
	evaluatesWithConfusionMatrix: 'Évalué avec une matrice de confusion',
	calibratesProbabilities: 'Calibre les probabilités',
	labeledContinuousTarget: 'Cible continue étiquetée',
	evaluatesWithResiduals: 'Évalué avec les résidus',
	sensitiveToScaleInLinear: 'Sensible à l’échelle (modèles linéaires)',
	unboundedNumericOutput: 'Sortie numérique non bornée',
	highDimensionalData: 'Données de grande dimension',
	preservesVarianceOrDistances: 'Préserve la variance ou les distances',
	featureScalingRequired: 'Mise à l’échelle des variables requise',
	foundationalTaxonomy: 'Taxonomie fondamentale',
	determinesDataCollection: 'Détermine la collecte des données',
	multiLayeredANNs: 'Réseaux de neurones multicouches',
	automaticFeatureExtraction: 'Extraction automatique des caractéristiques',
	computationalIntensityGPU: 'Calcul intensif (GPU)',
	dataHungry: 'Gourmand en données',
	differentiableForGradients: 'Différentiable pour les gradients',
	lowerIsBetter: 'Plus c’est bas, mieux c’est',
	guidesParameterUpdates: 'Guide la mise à jour des paramètres',
	differentiableCostFunction: 'Fonction de coût différentiable',
	requiresLearningRateTuning: 'Nécessite de régler le taux d’apprentissage',
	iterativeConvergence: 'Convergence itérative',
	domainKnowledge: 'Connaissance du domaine',
	mustPreventDataLeakage: 'Doit éviter la fuite de données',
	alignsWithModelAssumptions: 'Respecte les hypothèses du modèle',
	dataMovementPattern: 'Schéma de déplacement des données',
	determinesStorageStrategy: 'Détermine la stratégie de stockage',
	scalingRequired: 'Mise à l’échelle requise',
	handlesMissing: 'Gère les valeurs manquantes',
	outlierSensitive: 'Sensible aux valeurs aberrantes',
	linearRelationship: 'Relation linéaire',
	readOptimized: 'Optimisé pour la lecture',
	writeOptimized: 'Optimisé pour l’écriture',
	supportsCompression: 'Prend en charge la compression',
	schemaEvolution: 'Évolution du schéma',
	realTime: 'Temps réel',
	highThroughput: 'Haut débit',
	durableStorage: 'Stockage durable',
	orderedPerPartition: 'Ordonné par partition',
	distributed: 'Distribué',
	inMemoryCompute: 'Calcul en mémoire',
	lazyEvaluation: 'Évaluation paresseuse',
	faultTolerant: 'Tolérant aux pannes',
	acidTransactions: 'Transactions ACID',
	timeTravel: 'Voyage dans le temps (versions)',
	lowCostStorage: 'Stockage à faible coût',
	pythonCodeAsConfiguration: 'Configuration en code Python',
	dependencyTracking: 'Suivi des dépendances',
	backfillingSupport: 'Prise en charge du rattrapage (backfill)',
	retryLogic: 'Logique de relance',
	diagnosticPrinciple: 'Principe de diagnostic',
	guidesRegularization: 'Guide la régularisation',
	mustFitOnTrainOnly: 'À ajuster sur l’entraînement seulement',
	preservesOutliersWithRobust: 'Préserve les valeurs aberrantes (scaler robuste)',
	gpuAcceleration: 'Accélération GPU',
	massivePretrainingData: 'Données de pré-entraînement massives',
	positionalEncoding: 'Encodage positionnel',
	continuousTelemetry: 'Télémétrie continue',
	baselineReferenceData: 'Données de référence',
	statisticalTesting: 'Tests statistiques',
	regressionMetric: 'Métrique de régression',
	penalizesLargeErrors: 'Pénalise les grandes erreurs',
	sameUnitsAsTarget: 'Même unité que la cible',
	normalizedScore: 'Score normalisé',
	comparedToMeanBaseline: 'Comparé à la moyenne comme référence',
	outlierRobust: 'Robuste aux valeurs aberrantes',
	linearPenalty: 'Pénalité linéaire',
	classificationMetric: 'Métrique de classification',
	thresholdIndependent: 'Indépendant du seuil',
	requiresProbabilityOutput: 'Nécessite des probabilités en sortie',
	differentiable: 'Différentiable',
	usedAsLossFunction: 'Utilisé comme fonction de perte',
	unsupervisedMetric: 'Métrique non supervisée',
	noLabelsRequired: 'Aucune étiquette requise',
	distanceBased: 'Basé sur les distances',
	classificationDiagnostic: 'Diagnostic de classification',
	revealsMistakeTypes: 'Révèle les types d’erreurs',
	foundationForAllMetrics: 'Base de toutes les métriques',
	handlesNumerical: 'Gère les variables numériques',
	computationallyExpensive: 'Coûteux en calcul',
	universalStrategy: 'Stratégie universelle',
	fastAndSimple: 'Rapide et simple',
	categoricalToNumerical: 'Catégoriel vers numérique',
	preventsFalseOrdering: 'Évite un faux ordre',
	matchesAlgorithmExpectation: 'Correspond aux attentes de l’algorithme',
	preventDataLeakage: 'Éviter la fuite de données',
	honestEvaluation: 'Évaluation honnête',
	splitBeforePreprocessing: 'Découper avant le prétraitement',
	multipleTrainTestRounds: 'Plusieurs tours entraînement / test',
	robustPerformanceEstimate: 'Estimation robuste des performances',
	standardForHyperparameterTuning: 'Standard pour le réglage des hyperparamètres',
	preventsOverfitting: 'Évite le surapprentissage',
	addsToLossFunction: 'S’ajoute à la fonction de perte',
	controlledByHyperparameter: 'Contrôlé par un hyperparamètre',
	requiresCrossValidation: 'Nécessite une validation croisée',
	searchesParameterSpace: 'Explore l’espace des paramètres',
	preventsTestSetContamination: 'Évite de contaminer le jeu de test',
	diagnosticFramework: 'Cadre de diagnostic',
	comparesTrainVsValError: 'Compare erreur d’entraînement et de validation',
	guidesModelComplexity: 'Guide la complexité du modèle',
	requiresClearBusinessMetric: 'Nécessite une métrique métier claire',
	iterative: 'Itératif',
	assumesIndependentSamples: 'Suppose des échantillons indépendants',
	numericInputsOnly: 'Entrées numériques uniquement',
	versionControl: 'Gestion de versions',
	maturityLevel: 'Niveau de maturité',
	trackingServer: 'Serveur de suivi',
	reproducibleSeeds: 'Graines aléatoires reproductibles',
	latencyBudget: 'Budget de latence',
	trainingServingConsistency: 'Cohérence entraînement / production',
	pinnedDependencies: 'Dépendances figées',
	gpuSupport: 'Prise en charge GPU',
	automatedTests: 'Tests automatisés',
	evaluationGate: 'Seuil d’évaluation',
	pointInTimeCorrectness: 'Exactitude à date (point-in-time)',
	onlineStore: 'Magasin en ligne',
	trafficRouting: 'Routage du trafic',
	randomizedAssignment: 'Affectation aléatoire',
	schemaOnWrite: 'Schéma à l’écriture',
	supportsUnstructured: 'Prend en charge les données non structurées',
	storageLayout: 'Organisation du stockage',
	normalized: 'Normalisé',
	surrogateKeys: 'Clés de substitution',
	grainDefined: 'Granularité définie',
	latency: 'Latence',
	needsReplayableLog: 'Nécessite un journal rejouable',
	needsTransactionLog: 'Nécessite un journal de transactions',
	orderedPerKey: 'Ordonné par clé',
	needsWarehouse: 'Nécessite un entrepôt de données',
	sqlFirst: 'SQL d’abord',
	blocksPipelineOnFailure: 'Bloque le pipeline en cas d’échec',
	needsBaseline: 'Nécessite une référence',
	skewSensitive: 'Sensible au déséquilibre (skew)',
	targetFileSize: 'Taille de fichier cible',
	thresholdDependent: 'Dépend du seuil',
	needsPositiveClassDefined: 'Nécessite une classe positive définie',
	needsScoresNotLabels: 'Nécessite des scores, pas des étiquettes',
	resampleTrainOnly: 'Rééchantillonner l’entraînement seulement',
	needsStratifiedSplit: 'Nécessite un découpage stratifié',
	fitInsideCV: 'Ajuster dans la validation croisée',
	modelAgnostic: 'Indépendant du modèle',
	needsHeldOutData: 'Nécessite des données mises de côté',
	needsDiverseBaseModels: 'Nécessite des modèles de base variés',
	hurtsDistanceBasedModels: 'Pénalise les modèles à distance',
	noShuffling: 'Pas de mélange',
	sortedByTime: 'Trié par date',
	handlesCategorical: 'Gère les variables catégorielles',
	needsK: 'Nécessite k',
	deterministic: 'Déterministe',
	needsLabels: 'Nécessite des étiquettes',
	stationarityRequired: 'Stationnarité requise',
	coldStartProblem: 'Problème du démarrage à froid',
	needsEnvironment: 'Nécessite un environnement',
	learningRateSchedule: 'Planification du taux d’apprentissage',
	validationSetRequired: 'Jeu de validation requis',
	needsLargeCorpus: 'Nécessite un grand corpus',
	pretrainedModelRequired: 'Modèle pré-entraîné requis',
	labelsRequired: 'Étiquettes requises',
	contextWindowLimited: 'Fenêtre de contexte limitée',
	vectorDatabase: 'Base de données vectorielle',
	embeddingModel: 'Modèle d’embeddings'
};

const ar: Record<string, string> = {
	umbrellaField: 'مجال شامل',
	subsumesMLandDL: 'يشمل التعلم الآلي والتعلم العميق',
	includesRuleBasedSystems: 'يشمل الأنظمة القائمة على القواعد',
	requiresDataOrHeuristics: 'يتطلب بيانات أو قواعد استدلالية',
	requiresQualityData: 'يتطلب بيانات عالية الجودة',
	probabilisticOutput: 'مخرجات احتمالية',
	generalizationGoal: 'هدفه التعميم',
	avoidsHardcodedRules: 'يتجنب القواعد المكتوبة يدويًا',
	dataInfrastructure: 'بنية تحتية للبيانات',
	pipelineOrchestration: 'تنسيق خطوط المعالجة',
	dataQualityEnforcement: 'فرض جودة البيانات',
	schemaGovernance: 'حوكمة المخططات',
	unlabeledDataOnly: 'بيانات غير معنونة فقط',
	requiresDistanceMetric: 'يتطلب مقياس مسافة',
	featureScalingCritical: 'تحجيم الميزات حاسم',
	noGroundTruthLabels: 'لا عناوين مرجعية',
	labeledTrainingData: 'بيانات تدريب معنونة',
	discreteTargetClasses: 'فئات هدف منفصلة',
	evaluatesWithConfusionMatrix: 'يُقيَّم بمصفوفة الالتباس',
	calibratesProbabilities: 'يعاير الاحتمالات',
	labeledContinuousTarget: 'هدف مستمر معنون',
	evaluatesWithResiduals: 'يُقيَّم بالبواقي',
	sensitiveToScaleInLinear: 'حساس للمقياس (النماذج الخطية)',
	unboundedNumericOutput: 'مخرجات عددية غير محدودة',
	highDimensionalData: 'بيانات عالية الأبعاد',
	preservesVarianceOrDistances: 'يحافظ على التباين أو المسافات',
	featureScalingRequired: 'تحجيم الميزات مطلوب',
	foundationalTaxonomy: 'تصنيف تأسيسي',
	determinesDataCollection: 'يحدد طريقة جمع البيانات',
	multiLayeredANNs: 'شبكات عصبية متعددة الطبقات',
	automaticFeatureExtraction: 'استخراج تلقائي للميزات',
	computationalIntensityGPU: 'كثيف الحوسبة (GPU)',
	dataHungry: 'يحتاج إلى بيانات كثيرة',
	differentiableForGradients: 'قابل للاشتقاق لحساب التدرجات',
	lowerIsBetter: 'الأقل أفضل',
	guidesParameterUpdates: 'يوجّه تحديث المعاملات',
	differentiableCostFunction: 'دالة تكلفة قابلة للاشتقاق',
	requiresLearningRateTuning: 'يتطلب ضبط معدل التعلم',
	iterativeConvergence: 'تقارب تكراري',
	domainKnowledge: 'معرفة بالمجال',
	mustPreventDataLeakage: 'يجب منع تسرّب البيانات',
	alignsWithModelAssumptions: 'يتوافق مع افتراضات النموذج',
	dataMovementPattern: 'نمط نقل البيانات',
	determinesStorageStrategy: 'يحدد استراتيجية التخزين',
	scalingRequired: 'التحجيم مطلوب',
	handlesMissing: 'يتعامل مع القيم المفقودة',
	outlierSensitive: 'حساس للقيم الشاذة',
	linearRelationship: 'علاقة خطية',
	readOptimized: 'محسَّن للقراءة',
	writeOptimized: 'محسَّن للكتابة',
	supportsCompression: 'يدعم الضغط',
	schemaEvolution: 'تطوّر المخطط',
	realTime: 'زمن حقيقي',
	highThroughput: 'إنتاجية عالية',
	durableStorage: 'تخزين دائم',
	orderedPerPartition: 'مرتّب داخل كل قسم',
	distributed: 'موزَّع',
	inMemoryCompute: 'حوسبة في الذاكرة',
	lazyEvaluation: 'تقييم كسول',
	faultTolerant: 'متحمّل للأعطال',
	acidTransactions: 'معاملات ACID',
	timeTravel: 'السفر عبر الزمن (الإصدارات)',
	lowCostStorage: 'تخزين منخفض التكلفة',
	pythonCodeAsConfiguration: 'الإعداد بشيفرة Python',
	dependencyTracking: 'تتبع الاعتماديات',
	backfillingSupport: 'دعم المعالجة الاستدراكية (backfill)',
	retryLogic: 'منطق إعادة المحاولة',
	diagnosticPrinciple: 'مبدأ تشخيصي',
	guidesRegularization: 'يوجّه التنظيم (regularization)',
	mustFitOnTrainOnly: 'يُدرَّب على بيانات التدريب فقط',
	preservesOutliersWithRobust: 'يحافظ على القيم الشاذة (مُحجِّم متين)',
	gpuAcceleration: 'تسريع GPU',
	massivePretrainingData: 'بيانات تدريب مسبق ضخمة',
	positionalEncoding: 'ترميز موضعي',
	continuousTelemetry: 'قياس عن بُعد مستمر',
	baselineReferenceData: 'بيانات مرجعية أساسية',
	statisticalTesting: 'اختبارات إحصائية',
	regressionMetric: 'مقياس انحدار',
	penalizesLargeErrors: 'يعاقب الأخطاء الكبيرة',
	sameUnitsAsTarget: 'بنفس وحدة الهدف',
	normalizedScore: 'درجة مُطبَّعة',
	comparedToMeanBaseline: 'يُقارن بالمتوسط كمرجع',
	outlierRobust: 'متين أمام القيم الشاذة',
	linearPenalty: 'عقوبة خطية',
	classificationMetric: 'مقياس تصنيف',
	thresholdIndependent: 'مستقل عن العتبة',
	requiresProbabilityOutput: 'يتطلب مخرجات احتمالية',
	differentiable: 'قابل للاشتقاق',
	usedAsLossFunction: 'يُستخدم دالةَ خسارة',
	unsupervisedMetric: 'مقياس غير خاضع للإشراف',
	noLabelsRequired: 'لا يتطلب عناوين',
	distanceBased: 'قائم على المسافات',
	classificationDiagnostic: 'تشخيص للتصنيف',
	revealsMistakeTypes: 'يكشف أنواع الأخطاء',
	foundationForAllMetrics: 'أساس كل المقاييس',
	handlesNumerical: 'يتعامل مع المتغيرات العددية',
	computationallyExpensive: 'مكلف حسابيًا',
	universalStrategy: 'استراتيجية عامة',
	fastAndSimple: 'سريع وبسيط',
	categoricalToNumerical: 'من فئوي إلى عددي',
	preventsFalseOrdering: 'يمنع الترتيب الزائف',
	matchesAlgorithmExpectation: 'يطابق ما تتوقعه الخوارزمية',
	preventDataLeakage: 'منع تسرّب البيانات',
	honestEvaluation: 'تقييم نزيه',
	splitBeforePreprocessing: 'التقسيم قبل المعالجة المسبقة',
	multipleTrainTestRounds: 'جولات تدريب / اختبار متعددة',
	robustPerformanceEstimate: 'تقدير متين للأداء',
	standardForHyperparameterTuning: 'معيار لضبط المعاملات الفائقة',
	preventsOverfitting: 'يمنع الإفراط في التخصيص',
	addsToLossFunction: 'يُضاف إلى دالة الخسارة',
	controlledByHyperparameter: 'يُتحكَّم به بمعامل فائق',
	requiresCrossValidation: 'يتطلب التحقق المتقاطع',
	searchesParameterSpace: 'يبحث في فضاء المعاملات',
	preventsTestSetContamination: 'يمنع تلويث مجموعة الاختبار',
	diagnosticFramework: 'إطار تشخيصي',
	comparesTrainVsValError: 'يقارن خطأ التدريب بخطأ التحقق',
	guidesModelComplexity: 'يوجّه تعقيد النموذج',
	requiresClearBusinessMetric: 'يتطلب مقياس عمل واضحًا',
	iterative: 'تكراري',
	assumesIndependentSamples: 'يفترض عينات مستقلة',
	numericInputsOnly: 'مدخلات عددية فقط',
	versionControl: 'إدارة الإصدارات',
	maturityLevel: 'مستوى النضج',
	trackingServer: 'خادم التتبع',
	reproducibleSeeds: 'بذور عشوائية قابلة للتكرار',
	latencyBudget: 'ميزانية زمن الاستجابة',
	trainingServingConsistency: 'اتساق التدريب والخدمة',
	pinnedDependencies: 'اعتماديات مثبّتة الإصدار',
	gpuSupport: 'دعم GPU',
	automatedTests: 'اختبارات آلية',
	evaluationGate: 'بوابة التقييم',
	pointInTimeCorrectness: 'صحة البيانات في لحظة زمنية',
	onlineStore: 'مخزن مباشر (online)',
	trafficRouting: 'توجيه حركة المرور',
	randomizedAssignment: 'توزيع عشوائي',
	schemaOnWrite: 'المخطط عند الكتابة',
	supportsUnstructured: 'يدعم البيانات غير المهيكلة',
	storageLayout: 'تنظيم التخزين',
	normalized: 'مُطبَّع',
	surrogateKeys: 'مفاتيح بديلة',
	grainDefined: 'مستوى التفصيل محدد',
	latency: 'زمن الاستجابة',
	needsReplayableLog: 'يحتاج سجلًا قابلًا لإعادة التشغيل',
	needsTransactionLog: 'يحتاج سجل معاملات',
	orderedPerKey: 'مرتّب لكل مفتاح',
	needsWarehouse: 'يحتاج مستودع بيانات',
	sqlFirst: 'SQL أولًا',
	blocksPipelineOnFailure: 'يوقف خط المعالجة عند الفشل',
	needsBaseline: 'يحتاج مرجعًا أساسيًا',
	skewSensitive: 'حساس للالتواء (skew)',
	targetFileSize: 'حجم الملف المستهدف',
	thresholdDependent: 'يعتمد على العتبة',
	needsPositiveClassDefined: 'يحتاج تحديد الفئة الموجبة',
	needsScoresNotLabels: 'يحتاج درجات لا عناوين',
	resampleTrainOnly: 'إعادة المعاينة على التدريب فقط',
	needsStratifiedSplit: 'يحتاج تقسيمًا طبقيًا',
	fitInsideCV: 'التدريب داخل التحقق المتقاطع',
	modelAgnostic: 'مستقل عن النموذج',
	needsHeldOutData: 'يحتاج بيانات محجوزة',
	needsDiverseBaseModels: 'يحتاج نماذج أساسية متنوعة',
	hurtsDistanceBasedModels: 'يضر بالنماذج القائمة على المسافات',
	noShuffling: 'دون خلط',
	sortedByTime: 'مرتّب زمنيًا',
	handlesCategorical: 'يتعامل مع المتغيرات الفئوية',
	needsK: 'يحتاج تحديد k',
	deterministic: 'حتمي',
	needsLabels: 'يحتاج عناوين',
	stationarityRequired: 'الاستقرارية مطلوبة',
	coldStartProblem: 'مشكلة البداية الباردة',
	needsEnvironment: 'يحتاج بيئة',
	learningRateSchedule: 'جدولة معدل التعلم',
	validationSetRequired: 'مجموعة تحقق مطلوبة',
	needsLargeCorpus: 'يحتاج مدوّنة نصوص كبيرة',
	pretrainedModelRequired: 'نموذج مدرَّب مسبقًا مطلوب',
	labelsRequired: 'العناوين مطلوبة',
	contextWindowLimited: 'نافذة سياق محدودة',
	vectorDatabase: 'قاعدة بيانات متجهية',
	embeddingModel: 'نموذج تضمينات'
};

const labels: Partial<Record<Lang, Record<string, string>>> = { fr, ar };

/** Readable label for a requirements key in the given language. */
export function requirementLabel(key: string, lang: Lang): string {
	return labels[lang]?.[key] ?? formatKey(key);
}
