// Generated by tools/concept-index-plugin.ts
declare module 'virtual:concept-index' {
	const index: import('#lib/types.ts').ConceptMeta[];
	/** Translated index fields per language and concept id. */
	export const translations: Record<
		'fr' | 'ar',
		Record<string, Partial<Pick<import('#lib/types.ts').ConceptMeta, 'name' | 'category' | 'task' | 'summary' | 'searchText'>>>
	>;
	export default index;
}
